In [1]:
from policyengine.models import *
from policyengine.database import Database

db = Database(url="postgresql://postgres:postgres@127.0.0.1:54322/postgres")

In [9]:
current_law = db.get(Policy, name="Current law", country="uk")
static = db.get(Dynamic, name="Static", country="uk")
frs_2029 = db.get(Dataset, name="frs_2023_24/2029")

In [11]:
sim = Simulation(
    policy=current_law,
    dynamic=static,
    dataset=frs_2029,
    country="uk",
    model_version="2"
)

In [12]:
sim.run()

Dataset(id=UUID('ca839fbf-e0aa-4e79-a267-8a443bacc039'), name='frs_2023_24/2029', source_dataset=None, version=None, data=SingleYearDataset(tables={'person':        person_id  person_benunit_id  person_household_id   age  birth_year  \
0           1001                101                    1  66.0      1957.0
0           2003                201                    2   9.0      2014.0
1           2004                201                    2   4.0      2019.0
1           2001                201                    2  33.0      1990.0
2           2002                201                    2  33.0      1990.0
...          ...                ...                  ...   ...         ...
28585   16752001            1675201                16752  62.0      1961.0
28586   16753001            1675301                16753  46.0      1977.0
28587   16753002            1675302                16753  17.0      2006.0
28588   16754001            1675401                16754  24.0      1999.0
28589   16754002            1675402                16754  55.0      1968.0

       gender  hours_worked  is_household_head  is_benunit_head  \
0      FEMALE        2340.0               True             True
0      FEMALE           0.0              False            False
1      FEMALE           0.0              False            False
1      FEMALE        1430.0              False            False
2        MALE        1560.0               True             True
...       ...           ...                ...              ...
28585  FEMALE        1924.0               True             True
28586  FEMALE        2080.0               True             True
28587  FEMALE        2080.0              False             True
28588    MALE        2080.0               True             True
28589  FEMALE           0.0              False             True

      marital_status  ... maintenance_expenses childcare_expenses  \
0           DIVORCED  ...                  0.0                0.0
0             SINGLE  ...                  0.0                0.0
1             SINGLE  ...                  0.0                0.0
1            MARRIED  ...                  0.0                0.0
2            MARRIED  ...                  0.0                0.0
...              ...  ...                  ...                ...
28585      SEPARATED  ...                  0.0                0.0
28586       DIVORCED  ...                  0.0                0.0
28587         SINGLE  ...                  0.0                0.0
28588         SINGLE  ...                  0.0                0.0
28589      SEPARATED  ...                  0.0                0.0

       personal_pension_contributions  employee_pension_contributions  \
0                                 0.0                        0.000000
0                                 0.0                        0.000000
1                                 0.0                        0.000000
1                                 0.0                      906.949940
2                                 0.0                        0.000000
...                               ...                             ...
28585                             0.0                     2373.247259
28586                             0.0                        0.000000
28587                             0.0                        0.000000
28588                             0.0                     2657.468487
28589                             0.0                        0.000000

       employer_pension_contributions  is_disabled_for_benefits  \
0                            0.000000                     False
0                            0.000000                     False
1                            0.000000                     False
1                         2720.849821                     False
2                            0.000000                     False
...                               ...                       ...
28585                     7119.741776                     False
28586                        0.000000                     False
28587                        0.000000                     False
28588                     7972.405462                     False
28589                        0.000000                     False

       is_enhanced_disabled_for_benefits  is_severely_disabled_for_benefits  \
0                                  False                              False
0                                  False                              False
1                                  False                              False
1                                  False                              False
2                                  False                              False
...                                  ...                                ...
28585                              False                              False
28586                              False                              False
28587                              False                              False
28588                              False                              False
28589                              False                              False

       is_higher_earner  attends_private_school
0                  True                   False
0                 False                   False
1                 False                   False
1                  True                   False
2                 False                   False
...                 ...                     ...
28585              True                   False
28586              True                   False
28587              True                   False
28588              True                   False
28589              True                   False

[36248 rows x 71 columns], 'benunit':        benunit_id  would_claim_pc  would_claim_uc  would_claim_child_benefit  \
0             101           False            True                       True
1             201           False           False                       True
2             301           False            True                      False
3             401            True           False                      False
4             402           False            True                      False
...           ...             ...             ...                        ...
19369     1675201           False            True                       True
19370     1675301           False           False                       True
19371     1675302           False           False                       True
19372     1675401           False            True                       True
19373     1675402           False            True                       True

       would_claim_extended_childcare  would_claim_tfc  \
0                                True            False
1                               False            False
2                                True             True
3                                True             True
4                                True            False
...                               ...              ...
19369                           False            False
19370                            True             True
19371                            True            False
19372                           False             True
19373                            True             True

       would_claim_universal_childcare  would_claim_targeted_childcare  \
0                                 True                           False
1                                 True                           False
2                                False                            True
3                                False                           False
4                                 True                            True
...                                ...                             ...
19369                             True                            True
19370                            False                            True
19371                            False                           False
19372                            False                           False
19373                            False                            True

       maximum_extended_childcare_hours_usage
0                                   12.575289
1                                   19.804017
2                                   10.850478
3                                   16.271099
4                                   17.847392
...                                       ...
19369                               23.113464
19370                                8.760100
19371                                4.071130
19372                                9.264017
19373                               14.533665

[19374 rows x 9 columns], 'household':        household_id  household_weight            region          tenure_type  \
0                 1       1755.138357        SOUTH_EAST       OWNED_OUTRIGHT
1                 2       1632.061478             WALES  OWNED_WITH_MORTGAGE
2                 3       2059.210648        SOUTH_EAST  OWNED_WITH_MORTGAGE
3                 4       2474.982963        SOUTH_EAST    RENT_FROM_COUNCIL
4                 5       1613.444807     EAST_MIDLANDS       RENT_PRIVATELY
...             ...               ...               ...                  ...
16749         16750       1965.093034        SOUTH_EAST  OWNED_WITH_MORTGAGE
16750         16751       3843.308270   EAST_OF_ENGLAND       RENT_PRIVATELY
16751         16752        300.969512  NORTHERN_IRELAND       OWNED_OUTRIGHT
16752         16753       2330.186634          SCOTLAND         RENT_FROM_HA
16753         16754       3540.270239   EAST_OF_ENGLAND       RENT_PRIVATELY

        accommodation_type  council_tax council_tax_band  domestic_rates  \
0                     FLAT  1683.654263                C             0.0
1           HOUSE_TERRACED  2064.398465                C             0.0
2           HOUSE_DETACHED  2730.183800                D             0.0
3      HOUSE_SEMI_DETACHED  2318.604092                C             0.0
4           HOUSE_DETACHED  1813.486089                A             0.0
...                    ...          ...              ...             ...
16749       HOUSE_DETACHED  3283.063369                E             0.0
16750       HOUSE_TERRACED  1400.752258                B             0.0
16751       HOUSE_TERRACED     0.000000                A           572.0
16752       HOUSE_TERRACED  2229.505929                D             0.0
16753                 FLAT  2466.954882                C             0.0

               rent  mortgage_interest_repayment  mortgage_capital_repayment  \
0          0.000000                     0.000000                    0.000000
1          0.000000                  6324.261128                 4827.284360
2          0.000000                 10155.989991                51289.896325
3       7523.368061                     0.000000                    0.000000
4          0.000000                     0.000000                    0.000000
...             ...                          ...                         ...
16749      0.000000                 12756.622573                25343.242890
16750   9618.785596                     0.000000                    0.000000
16751      0.000000                     0.000000                    0.000000
16752   9485.985815                     0.000000                    0.000000
16753  17380.150525                     0.000000                    0.000000

       housing_service_charges  structural_insurance_payments  \
0                   1351.22541                     106.780738
1                      0.00000                     177.635246
2                      0.00000                     226.534836
3                      0.00000                       0.000000
4                      0.00000                       0.000000
...                        ...                            ...
16749                  0.00000                     349.282787
16750                  0.00000                       0.000000
16751                  0.00000                     348.284836
16752                  0.00000                       0.000000
16753                  0.00000                       0.000000

       water_and_sewerage_charges  external_child_payments  \
0                      216.019286                      0.0
1                      786.331071                      0.0
2                      367.858929                      0.0
3                      225.933214                      0.0
4                      324.028929                      0.0
...                           ...                      ...
16749                  648.057857                      0.0
16750                  239.499643                      0.0
16751                    0.000000                      0.0
16752                  477.955714                      0.0
16753                  227.498571                      0.0

                     brma  would_evade_tv_licence_fee  \
0              CANTERBURY                       False
1                 WREXHAM                       False
2           DOVER_SHEPWAY                       False
3                  THANET                       False
4                 LINCOLN                       False
...                   ...                         ...
16749          CHICHESTER                       False
16750          HUNTINGDON                       False
16751             BELFAST                       False
16752  ABERDEEN_AND_SHIRE                        True
16753          COLCHESTER                       False

       main_residential_property_purchased_is_first_home  household_owns_tv
0                                                  False               True
1                                                  False               True
2                                                  False               True
3                                                  False               True
4                                                  False               True
...                                                  ...                ...
16749                                              False               True
16750                                               True               True
16751                                              False               True
16752                                              False               True
16753                                              False               True

[16754 rows x 19 columns]}, year=2029), dataset_type=<DatasetType.UK: 'uk'>)

In [ ]:
db.add(sim)